account: stf
partition: cpu-g2-mem2x
nodes: 1
cores: 1
walltime: '12:00:00'
mem: 110G
jobname: 'structural_info_{pdb_list_filename}_{which_charges}_{relaxation}_{relaxation_num}'
logdir: logs

input_parent_dir: /gscratch/stf/gvisan01/casp12
output_parent_dir: /gscratch/stf/gvisan01/casp12


parameters:

  which_charges: [pyrosetta]

  relaxation: [None]
  relaxation_num: [0]

  pdb_list_filename: [casp12_training__0, casp12_training__1, casp12_training__2, casp12_training__3, casp12_training__4, casp12_training__5, casp12_training__6, casp12_training__7, casp12_training__8, casp12_training__9, casp12_validation, casp12_testing]
  
  pdb_dir: [/gscratch/stf/gvisan01/casp12/pdbs]

  
command: |
  cd /gscratch/spe/gvisan01/protein_holography-pytorch/protein_holography_pytorch/preprocessing_faster

  python -u get_structural_info.py \
                        --pdb_dir {pdb_dir} \
                        --pdb_list_file {input_parent_dir}/pdb_lists/{pdb_list_filename}.txt \
                        --hdf5_out {output_parent_dir}/structural_info/structural_info-{pdb_list_filename}-charges={which_charges}-noise=0_0-relaxation={relaxation}_{relaxation_num}.hdf5 \
                        --which_charges {which_charges} \
                        --relaxation {relaxation} \
                        --parallelism {cores} \
                        --logging DEBUG
  
# mv /gscratch/stf/gvisan01/casp12/structural_info/structural_info-casp12_training__0-charges=pyrosetta-noise=0_0-relaxation=sidechains_0.hdf5 /gscratch/stf/gvisan01/casp12/structural_info/structural_info-casp12_training__0-charges=pyrosetta-noise=0_0-relaxation=None_0.hdf5
# mv /gscratch/stf/gvisan01/casp12/structural_info/structural_info-casp12_training__1-charges=pyrosetta-noise=0_0-relaxation=sidechains_0.hdf5 /gscratch/stf/gvisan01/casp12/structural_info/structural_info-casp12_training__1-charges=pyrosetta-noise=0_0-relaxation=None_0.hdf5
# mv /gscratch/stf/gvisan01/casp12/structural_info/structural_info-casp12_training__2-charges=pyrosetta-noise=0_0-relaxation=sidechains_0.hdf5 /gscratch/stf/gvisan01/casp12/structural_info/structural_info-casp12_training__2-charges=pyrosetta-noise=0_0-relaxation=None_0.hdf5
# mv /gscratch/stf/gvisan01/casp12/structural_info/structural_info-casp12_training__3-charges=pyrosetta-noise=0_0-relaxation=sidechains_0.hdf5 /gscratch/stf/gvisan01/casp12/structural_info/structural_info-casp12_training__3-charges=pyrosetta-noise=0_0-relaxation=None_0.hdf5
# mv /gscratch/stf/gvisan01/casp12/structural_info/structural_info-casp12_training__4-charges=pyrosetta-noise=0_0-relaxation=sidechains_0.hdf5 /gscratch/stf/gvisan01/casp12/structural_info/structural_info-casp12_training__4-charges=pyrosetta-noise=0_0-relaxation=None_0.hdf5
# mv /gscratch/stf/gvisan01/casp12/structural_info/structural_info-casp12_training__5-charges=pyrosetta-noise=0_0-relaxation=sidechains_0.hdf5 /gscratch/stf/gvisan01/casp12/structural_info/structural_info-casp12_training__5-charges=pyrosetta-noise=0_0-relaxation=None_0.hdf5
# mv /gscratch/stf/gvisan01/casp12/structural_info/structural_info-casp12_training__6-charges=pyrosetta-noise=0_0-relaxation=sidechains_0.hdf5 /gscratch/stf/gvisan01/casp12/structural_info/structural_info-casp12_training__6-charges=pyrosetta-noise=0_0-relaxation=None_0.hdf5
# mv /gscratch/stf/gvisan01/casp12/structural_info/structural_info-casp12_training__7-charges=pyrosetta-noise=0_0-relaxation=sidechains_0.hdf5 /gscratch/stf/gvisan01/casp12/structural_info/structural_info-casp12_training__7-charges=pyrosetta-noise=0_0-relaxation=None_0.hdf5
# mv /gscratch/stf/gvisan01/casp12/structural_info/structural_info-casp12_training__8-charges=pyrosetta-noise=0_0-relaxation=sidechains_0.hdf5 /gscratch/stf/gvisan01/casp12/structural_info/structural_info-casp12_training__8-charges=pyrosetta-noise=0_0-relaxation=None_0.hdf5
# mv /gscratch/stf/gvisan01/casp12/structural_info/structural_info-casp12_training__9-charges=pyrosetta-noise=0_0-relaxation=sidechains_0.hdf5 /gscratch/stf/gvisan01/casp12/structural_info/structural_info-casp12_training__9-charges=pyrosetta-noise=0_0-relaxation=None_0.hdf5
# mv /gscratch/stf/gvisan01/casp12/structural_info/structural_info-casp12_validation-charges=pyrosetta-noise=0_0-relaxation=sidechains_0.hdf5 /gscratch/stf/gvisan01/casp12/structural_info/structural_info-casp12_validation-charges=pyrosetta-noise=0_0-relaxation=None_0.hdf5
# mv /gscratch/stf/gvisan01/casp12/structural_info/structural_info-casp12_testing-charges=pyrosetta-noise=0_0-relaxation=sidechains_0.hdf5 /gscratch/stf/gvisan01/casp12/structural_info/structural_info-casp12_testing-charges=pyrosetta-noise=0_0-relaxation=None_0.hdf5
