
account: stf
partition: cpu-g2-mem2x
nodes: 1
cores: 1
walltime: '12:00:00'
mem: 96G
jobname: 'noise_{pdb_list_filename}_{noise}_{seed}_{which_charges}_{relaxation}_{relaxation_num}'
logdir: logs

input_parent_dir: /gscratch/stf/gvisan01/casp12
output_parent_dir: /gscratch/stf/gvisan01/casp12


parameters:

  noise: [0.5]
  seed: [10000, 10001, 10002, 10003, 10004, 10005, 10006, 10007, 10008, 10009]

  which_charges: [pyrosetta]

  relaxation: [None]
  relaxation_num: [0]

  pdb_list_filename: [casp12_training__0, casp12_training__1, casp12_training__2, casp12_training__3, casp12_training__4, casp12_training__5, casp12_training__6, casp12_training__7, casp12_training__8, casp12_training__9, casp12_validation, casp12_testing]


  
command: |
  cd /gscratch/spe/gvisan01/protein_holography-pytorch/protein_holography_pytorch/preprocessing_faster
  
  python -u add_noise_to_structural_info.py \
                        --hdf5_in {input_parent_dir}/structural_info/structural_info-{pdb_list_filename}-charges={which_charges}-noise=0_0-relaxation={relaxation}_{relaxation_num}.hdf5 \
                        --hdf5_out {output_parent_dir}/structural_info/structural_info-{pdb_list_filename}-charges={which_charges}-noise={noise}_{seed}-relaxation={relaxation}_{relaxation_num}.hdf5 \
                        --noise {noise} \
                        --seed {seed}



