
# data hparams
data_filepath: '/gscratch/scrubbed/gvisan01/casp12/zernikegrams_larger/zernikegrams-no_central_{remove_central_what}-{pdb_list_filename}-r_max={rcut}-l_max={lmax}-radial_func_mode={radial_func_mode}-radial_func_max={radial_func_max}-channels={channels}-rst_normalization={rst_normalization}-charges={charges}-noise={noise}_{noise_seed}-relaxation={relaxation}_{relaxation_num}.hdf5'
remove_central_what: 'sidechain'
remove_central_residue: false
remove_central_sidechain: true
parser: pyrosetta
extra_molecules: true
num_train_datasets: 10
pdb_list_filename_template: 'casp12_{split}'
rcut: 12.5
lmax: 5
radial_func_mode: ks
radial_func_max: 12
channels: 'C,N,O,S,H,SASA,charge'
get_physicochemical_info_for_hydrogens: true
rst_normalization: 'square'
charges: pyrosetta
noise: None # set later
noise_seed: None # set later
relaxation: None
relaxation_num: 0
normalize_input: true

# model hparams
model_type: 'so3_convnet'
model_hparams: 
  output_dim: 20
  n_cg_blocks: 6
  n_fc_blocks: 1
  fc_h_dim: 256
  fc_nonlin: 'silu'
  dropout_rate: 0.0
  ch_size_list: [96, 96, 96, 96, 96, 256]
  ls_nonlin_rule_list: ['full', 'full', 'full', 'full', 'full', 'full']
  ch_nonlin_rule_list: ['elementwise', 'elementwise', 'elementwise', 'elementwise', 'elementwise', 'elementwise']
  do_initial_linear_projection: true
  ch_initial_linear_projection: 96
  lmax_list: [5, 5, 5, 5, 5, 0]
  use_additive_skip_connections: false
  use_batch_norm: false
  weights_initializer: null
  norm_type: layer_nonlin
  normalization: component
  norm_balanced: false
  norm_affine: true
  norm_nonlinearity: swish
  norm_location: between
  linearity_first: false
  filter_symmetric: true

# training hparams
n_epochs: 10
lr: 0.001
lr_scheduler: 'reduce_lr_on_plateau'
batch_size: 512

# rng seed, for reproducibility
seed: None # set later
