zernikegrams_npz_gz_template: 'training_data/finetuning/mega_thermompnn_neg/premade_zernikegrams/{model_version}.npz.gz' # output directory when generating zernikegrams
targets_csv_template: training_data/finetuning/mega_thermompnn_neg/{split}_targets.csv # targets, where {split} is either train, valid, or test
model_version: hermes_py_050_ft_casp12_perc0p5_relaxed_pred
finetuning_version: ft_mega_thermompnn_ddg_st # only added as suffix to the model version
score_col: score
finetuning_depth: all # 'all' or 'invariant_mlp'. Use 'all'
finetune_with_noise: true # whether you toggled `--add_noise` when generating zernikegrams
batch_size: 128
lr: 0.001
n_epochs: 15
alpha_gly: 0.0
lr_scheduler: reduce_lr_on_plateau